# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('cancellation_date', models.DateTimeField(default=None, verbose_name='Cancellation date')),
                ('activation_date', models.DateTimeField(default=None, verbose_name='Activation date')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
