# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='activation_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Activation date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Cancellation date'),
        ),
    ]
