# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20160501_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email_hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
